### ISSUE TITLE
how to run tests

### ISSUE THREAD

**Issue by weepy** [component/min#2]
hi , so I did : 

git clone
npm install 
component install
make test

but I get Error: Cannot find module 'to-function'

**Comment by retrofox** [comment]
@weepy you've to do 'make' to downlaod dependencies and build it

**Comment by weepy** [comment]
```
git clone git://github.com/component/min.git
cd min/
npm install
make test
```

"Error: Cannot find module 'to-function'"

**Comment by retrofox** [comment]
> @weepy you've to do 'make' to downlaod dependencies and build it

```
git clone git://github.com/component/min.git
cd min/
npm install
make
make test
```

**Comment by weepy** [comment]
did that - same error

**Comment by retrofox** [comment]
ups @weepy you're right

**Comment by tj** [comment]
my bad, forgot to add it to the package.json

**Comment by retrofox** [comment]
I added a symlink to node_modules/ to test it. Works but it's a bit lame.

**Comment by weepy** [comment]
um what's best practice here ? ... I thought it wasn't necessary rely on npm ?

**Comment by tj** [comment]
it's not, im just using npm for testing so i dont have to view them in the browser

**Comment by weepy** [comment]
perhaps there could be a special require-component that would traverse the
component.json, so we don't have to maintain two package managers.

**Comment by tj** [comment]
meh its not a big deal i was just lazy
